// import { Inter } from 'next/font/google'
import './globals.css'

import Form from "@/Common/Form/page"
import Headers from "@/Common/headers/index"
import Footer from "@/Common/Footer/page"
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Interiormaata',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
     
      <Headers/>
      {children}
      <Form/>
      <Footer/>
      </body>
    </html>
  )
}
